version: '3'
services:
  front-end:
    hostname: frontend
    image: dtdemos/dt-orders-frontend-node:1
    ports:
      - 80:8080
    environment:
      - CUSTOMER_URL=http://172.17.0.1:8181
      - CATALOG_URL=http://172.17.0.1:8182
      - ORDER_URL=http://172.17.0.1:8183
  customer-service:
    hostname: customer
    image: dtdemos/dt-orders-customer-service:1
    ports:
      - 8181:8080
  catalog-service:
    hostname: catalog
    image: dtdemos/dt-orders-catalog-service:1
    ports:
      - 8182:8080
  order-service:
    hostname: order
    image: dtdemos/dt-orders-order-service:1
    ports:
      - 8183:8080
    environment:
      - CUSTOMER_SERVICE_DOMAIN=172.17.0.1
      - CUSTOMER_SERVICE_PORT=8181
      - CATALOG_SERVICE_DOMAIN=172.17.0.1
      - CATALOG_SERVICE_PORT=8182