---
apiVersion: v1
kind: Service
metadata:
  name: easytravel-backend
  labels:   
    app: easytravel-backend
spec:
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: easytravel-backend
  type: LoadBalancer  

